/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DocumentEditorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  enableHeadingNumbers: true,
  enableFigureNumbers: true,
  enableTableNumbers: true,
  enableEquationNumbers: true,
  enableBibliography: true,
  bibNumberingOrder: "citation",
  defaultPdfFontSize: 11,
  defaultPdfMargin: 20,
  autoConvertWikiImages: true
};

// src/settingsTab.ts
var import_obsidian = require("obsidian");
var DocumentEditorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Document Editor Settings" });
    new import_obsidian.Setting(containerEl).setName("\u898B\u51FA\u3057\u81EA\u52D5\u756A\u53F7\u4ED8\u3051").setDesc("H1=1., H2=1.1, H3=1.1.1 \u5F62\u5F0F\u3067\u756A\u53F7\u3092\u8868\u793A\u3057\u307E\u3059\uFF08Markdown\u306F\u5909\u66F4\u3057\u307E\u305B\u3093\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableHeadingNumbers).onChange(async (value) => {
      this.plugin.settings.enableHeadingNumbers = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("wiki\u753B\u50CF\u30EA\u30F3\u30AF\u3092\u81EA\u52D5\u5909\u63DB").setDesc("![[image.png]] \u5F62\u5F0F\u3092 ![image](image.png) \u5F62\u5F0F\u306B\u81EA\u52D5\u5909\u63DB\u3057\u307E\u3059\uFF08\u30DA\u30FC\u30B9\u30C8\u6642\u306A\u3069\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoConvertWikiImages).onChange(async (value) => {
      this.plugin.settings.autoConvertWikiImages = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u56F3\u756A\u53F7\u3092\u81EA\u52D5\u4ED8\u4E0E").setDesc("\u753B\u50CF\u306B\u81EA\u52D5\u3067\u300C\u56F3N: \u30AD\u30E3\u30D7\u30B7\u30E7\u30F3\u300D\u3092\u8868\u793A\u3057\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableFigureNumbers).onChange(async (value) => {
      this.plugin.settings.enableFigureNumbers = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u8868\u756A\u53F7\u3092\u81EA\u52D5\u4ED8\u4E0E").setDesc("\u30C6\u30FC\u30D6\u30EB\u306B\u81EA\u52D5\u3067\u300C\u8868N\u300D\u3092\u8868\u793A\u3057\u3001\u4E2D\u592E\u63C3\u3048\u306B\u3057\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableTableNumbers).onChange(async (value) => {
      this.plugin.settings.enableTableNumbers = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6570\u5F0F\u756A\u53F7\u3092\u81EA\u52D5\u4ED8\u4E0E").setDesc("\u30D6\u30ED\u30C3\u30AF\u6570\u5F0F\u306B\u81EA\u52D5\u3067 (N) \u306E\u756A\u53F7\u3092\u4ED8\u3051\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableEquationNumbers).onChange(async (value) => {
      this.plugin.settings.enableEquationNumbers = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u53C2\u8003\u6587\u732E\u7BA1\u7406").setDesc("key\u30AB\u30E9\u30E0\u3092\u6301\u3064\u30C6\u30FC\u30D6\u30EB\u3092\u53C2\u8003\u6587\u732E\u3068\u3057\u3066\u81EA\u52D5\u756A\u53F7\u4ED8\u3051\u3057\u307E\u3059").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableBibliography).onChange(async (value) => {
      this.plugin.settings.enableBibliography = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u53C2\u8003\u6587\u732E\u306E\u756A\u53F7\u9806").setDesc("\u300C\u53C2\u7167\u9806\u300D: \u6587\u66F8\u5185\u3067\u6700\u521D\u306B\u53C2\u7167\u3055\u308C\u305F\u9806\u756A\u3002\u300C\u30C6\u30FC\u30D6\u30EB\u884C\u9806\u300D: \u30C6\u30FC\u30D6\u30EB\u306E\u884C\u9806\u756A").addDropdown((dropdown) => dropdown.addOption("citation", "\u53C2\u7167\u9806").addOption("table", "\u30C6\u30FC\u30D6\u30EB\u884C\u9806").setValue(this.plugin.settings.bibNumberingOrder).onChange(async (value) => {
      this.plugin.settings.bibNumberingOrder = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "PDF\u51FA\u529B\u30C7\u30D5\u30A9\u30EB\u30C8\u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u672C\u6587\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA (pt)").addSlider((slider) => slider.setLimits(9, 14, 1).setValue(this.plugin.settings.defaultPdfFontSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.defaultPdfFontSize = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u4F59\u767D (mm)").addSlider((slider) => slider.setLimits(10, 30, 5).setValue(this.plugin.settings.defaultPdfMargin).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.defaultPdfMargin = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/processors/headingNumberer.ts
var import_obsidian2 = require("obsidian");
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var HeadingCounter = class {
  constructor() {
    this.counts = [0, 0, 0, 0, 0, 0];
  }
  next(level) {
    this.counts[level - 1]++;
    this.counts.fill(0, level);
    return this.counts.slice(0, level).join(".") + ".";
  }
  reset() {
    this.counts.fill(0);
  }
};
var headingCounterMap = /* @__PURE__ */ new WeakMap();
var headingLastFileMap = /* @__PURE__ */ new WeakMap();
var HeadingNumberWidget = class extends import_view.WidgetType {
  constructor(number) {
    super();
    this.number = number;
  }
  toDOM() {
    const span = document.createElement("span");
    span.className = "de-heading-number";
    span.textContent = this.number + " ";
    return span;
  }
  eq(other) {
    return other.number === this.number;
  }
};
function parseHeadings(doc) {
  const text = doc.toString();
  const results = [];
  const lines = text.split("\n");
  let offset = 0;
  for (const line of lines) {
    const m = line.match(/^(#{1,6}) /);
    if (m) {
      const level = m[1].length;
      const from = offset + m[1].length + 1;
      results.push({ level, from });
    }
    offset += line.length + 1;
  }
  return results;
}
function buildHeadingDecorations(view) {
  const builder = new import_state.RangeSetBuilder();
  const counter = new HeadingCounter();
  const headings = parseHeadings(view.state.doc);
  for (const { level, from } of headings) {
    if (from > view.state.doc.length)
      continue;
    const number = counter.next(level);
    builder.add(
      from,
      from,
      import_view.Decoration.widget({
        widget: new HeadingNumberWidget(number),
        side: -1
      })
    );
  }
  return builder.finish();
}
function createHeadingNumberPlugin(plugin) {
  let debounceTimer = null;
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = plugin.settings.enableHeadingNumbers ? buildHeadingDecorations(view) : import_view.Decoration.none;
      }
      update(update) {
        if (!plugin.settings.enableHeadingNumbers) {
          this.decorations = import_view.Decoration.none;
          return;
        }
        if (update.docChanged || update.viewportChanged) {
          this.decorations = import_view.Decoration.none;
          if (debounceTimer)
            clearTimeout(debounceTimer);
          debounceTimer = setTimeout(() => {
            this.decorations = buildHeadingDecorations(update.view);
            update.view.dispatch({});
          }, 300);
        }
      }
    },
    { decorations: (v) => v.decorations }
  );
}
function registerHeadingPostProcessor(plugin) {
  plugin.registerMarkdownPostProcessor(
    (el, _ctx) => {
      var _a, _b;
      if (!plugin.settings.enableHeadingNumbers)
        return;
      const activeView = plugin.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      if (!activeView)
        return;
      const contentEl = activeView.contentEl;
      let counter = headingCounterMap.get(contentEl);
      const lastFile = headingLastFileMap.get(contentEl);
      const currentFile = (_b = (_a = activeView.file) == null ? void 0 : _a.path) != null ? _b : "";
      if (!counter || lastFile !== currentFile) {
        counter = new HeadingCounter();
        headingCounterMap.set(contentEl, counter);
        headingLastFileMap.set(contentEl, currentFile);
      }
      const headings = el.querySelectorAll("h1,h2,h3,h4,h5,h6");
      headings.forEach((h) => {
        if (h.querySelector(".de-heading-number"))
          return;
        const level = parseInt(h.tagName[1], 10);
        const number = counter.next(level);
        const span = document.createElement("span");
        span.className = "de-heading-number";
        span.textContent = number + " ";
        h.insertBefore(span, h.firstChild);
      });
    },
    // Priority: run before other processors
    1
  );
}

// src/processors/figureProcessor.ts
var FigureCounter = class {
  constructor() {
    this.figureCount = 0;
    this.tableCount = 0;
  }
  reset() {
    this.figureCount = 0;
    this.tableCount = 0;
  }
  nextFigure() {
    return ++this.figureCount;
  }
  nextTable() {
    return ++this.tableCount;
  }
};
function isOnlyMeaningfulChild(el, parent) {
  return Array.from(parent.childNodes).every(
    (node) => {
      var _a;
      return node === el || node.nodeType === Node.TEXT_NODE && ((_a = node.textContent) != null ? _a : "").trim() === "";
    }
  );
}
function applyFigureWrap(target, captionText) {
  var _a, _b;
  const wrap = document.createElement("div");
  wrap.className = "de-figure";
  const caption = document.createElement("div");
  caption.className = "de-figcaption";
  caption.textContent = captionText;
  const parent = target.parentElement;
  if ((parent == null ? void 0 : parent.tagName) === "P" && isOnlyMeaningfulChild(target, parent)) {
    (_a = parent.parentNode) == null ? void 0 : _a.insertBefore(wrap, parent);
    wrap.appendChild(target);
    wrap.appendChild(caption);
    parent.remove();
  } else {
    (_b = target.parentNode) == null ? void 0 : _b.insertBefore(wrap, target);
    wrap.appendChild(target);
    wrap.appendChild(caption);
  }
}
function processFigures(el, counter) {
  const targets = [];
  el.querySelectorAll(".internal-embed.image-embed").forEach((embed) => {
    var _a, _b;
    if (embed.closest(".de-figure"))
      return;
    const img = embed.querySelector("img");
    const altText = (_b = (_a = img == null ? void 0 : img.alt) != null ? _a : embed.getAttribute("alt")) != null ? _b : "";
    targets.push({ node: embed, altText });
  });
  el.querySelectorAll("img").forEach((img) => {
    var _a;
    if (img.closest(".de-figure") || img.closest(".internal-embed"))
      return;
    targets.push({ node: img, altText: (_a = img.alt) != null ? _a : "" });
  });
  targets.sort((a, b) => {
    const pos = a.node.compareDocumentPosition(b.node);
    if (pos & Node.DOCUMENT_POSITION_FOLLOWING)
      return -1;
    if (pos & Node.DOCUMENT_POSITION_PRECEDING)
      return 1;
    return 0;
  });
  for (const { node, altText } of targets) {
    const n = counter.nextFigure();
    const captionText = altText ? `\u56F3${n}: ${altText}` : `\u56F3${n}`;
    applyFigureWrap(node, captionText);
  }
}
function processTables(el, counter) {
  el.querySelectorAll("table").forEach((table) => {
    var _a;
    if (table.closest(".de-table-wrap"))
      return;
    const n = counter.nextTable();
    const wrap = document.createElement("div");
    wrap.className = "de-table-wrap";
    const caption = document.createElement("div");
    caption.className = "de-table-caption";
    caption.textContent = `\u8868${n}`;
    (_a = table.parentNode) == null ? void 0 : _a.insertBefore(wrap, table);
    wrap.appendChild(caption);
    wrap.appendChild(table);
  });
}
function unwrapFigures(container) {
  container.querySelectorAll(".de-figure").forEach((wrap) => {
    const parent = wrap.parentNode;
    if (!parent)
      return;
    Array.from(wrap.children).forEach((child) => {
      if (!child.classList.contains("de-figcaption")) {
        parent.insertBefore(child, wrap);
      }
    });
    wrap.remove();
  });
}
function unwrapTables(container) {
  container.querySelectorAll(".de-table-wrap").forEach((wrap) => {
    const parent = wrap.parentNode;
    if (!parent)
      return;
    Array.from(wrap.children).forEach((child) => {
      if (!child.classList.contains("de-table-caption")) {
        parent.insertBefore(child, wrap);
      }
    });
    wrap.remove();
  });
}
function processFigureContainer(container, settings) {
  const { enableFigureNumbers, enableTableNumbers } = settings;
  if (!enableFigureNumbers && !enableTableNumbers)
    return;
  if (enableFigureNumbers)
    unwrapFigures(container);
  if (enableTableNumbers)
    unwrapTables(container);
  const counter = new FigureCounter();
  if (enableFigureNumbers)
    processFigures(container, counter);
  if (enableTableNumbers)
    processTables(container, counter);
}
var SESSION_GAP_MS = 500;
function registerFigurePostProcessor(plugin) {
  const counter = new FigureCounter();
  let lastCallTime = 0;
  let lastFile = "";
  plugin.registerMarkdownPostProcessor(
    (el, ctx) => {
      const { enableFigureNumbers, enableTableNumbers } = plugin.settings;
      if (!enableFigureNumbers && !enableTableNumbers)
        return;
      const now = Date.now();
      const currentFile = ctx.sourcePath;
      if (currentFile !== lastFile || now - lastCallTime > SESSION_GAP_MS) {
        counter.reset();
        lastFile = currentFile;
      }
      lastCallTime = now;
      if (enableFigureNumbers)
        processFigures(el, counter);
      if (enableTableNumbers)
        processTables(el, counter);
    },
    10
  );
}

// src/processors/wikiImageConverter.ts
var import_obsidian3 = require("obsidian");
var IMAGE_EXT_RE = /\.(png|jpg|jpeg|gif|webp|svg|bmp|tiff?)$/i;
var WIKI_IMAGE_RE = /!\[\[([^\]|]+(?:\|[^\]]*)?)\]\]/g;
function getRelativePath(fromFilePath, toFilePath) {
  const lastSlash = fromFilePath.lastIndexOf("/");
  const fromDir = lastSlash >= 0 ? fromFilePath.substring(0, lastSlash) : "";
  const fromParts = fromDir ? fromDir.split("/") : [];
  const toParts = toFilePath.split("/");
  let common = 0;
  while (common < fromParts.length && common < toParts.length - 1 && fromParts[common] === toParts[common]) {
    common++;
  }
  const ups = fromParts.slice(common).map(() => "..");
  const downs = toParts.slice(common);
  return [...ups, ...downs].join("/") || toFilePath;
}
function encodeMarkdownPath(relativePath) {
  return relativePath.split("/").map((seg) => encodeURIComponent(seg)).join("/");
}
function buildMarkdownImage(altText, relativePath) {
  return `![${altText}](${encodeMarkdownPath(relativePath)})`;
}
function replaceWikiLinksForFile(editor, sourceFilePath, targetFile) {
  const escapedName = targetFile.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(
    `!\\[\\[([^\\]|]*${escapedName}(?:\\|[^\\]]*)?)\\]\\]`,
    "g"
  );
  const lineCount = editor.lineCount();
  for (let lineNum = lineCount - 1; lineNum >= 0; lineNum--) {
    const line = editor.getLine(lineNum);
    if (!line.includes("![["))
      continue;
    const spans = [];
    let m;
    while ((m = re.exec(line)) !== null) {
      const inner = m[1];
      const pipeIdx = inner.indexOf("|");
      const alias = pipeIdx >= 0 ? inner.substring(pipeIdx + 1).trim() : void 0;
      const altText = alias != null ? alias : targetFile.basename;
      const relativePath = getRelativePath(sourceFilePath, targetFile.path);
      spans.push({ from: m.index, to: m.index + m[0].length, text: buildMarkdownImage(altText, relativePath) });
    }
    for (let i = spans.length - 1; i >= 0; i--) {
      const { from, to, text } = spans[i];
      editor.replaceRange(text, { line: lineNum, ch: from }, { line: lineNum, ch: to });
    }
  }
}
function replaceAllWikiLinksViaCache(editor, sourceFilePath, app) {
  const lineCount = editor.lineCount();
  for (let lineNum = lineCount - 1; lineNum >= 0; lineNum--) {
    const line = editor.getLine(lineNum);
    if (!line.includes("![["))
      continue;
    const spans = [];
    const re = new RegExp(WIKI_IMAGE_RE.source, "g");
    let m;
    while ((m = re.exec(line)) !== null) {
      const inner = m[1];
      const pipeIdx = inner.indexOf("|");
      const filePart = (pipeIdx >= 0 ? inner.substring(0, pipeIdx) : inner).trim();
      const alias = pipeIdx >= 0 ? inner.substring(pipeIdx + 1).trim() : void 0;
      if (!IMAGE_EXT_RE.test(filePart))
        continue;
      const file = app.metadataCache.getFirstLinkpathDest(filePart, sourceFilePath);
      if (!file)
        continue;
      const altText = alias != null ? alias : file.basename;
      const relativePath = getRelativePath(sourceFilePath, file.path);
      spans.push({ from: m.index, to: m.index + m[0].length, text: buildMarkdownImage(altText, relativePath) });
    }
    for (let i = spans.length - 1; i >= 0; i--) {
      const { from, to, text } = spans[i];
      editor.replaceRange(text, { line: lineNum, ch: from }, { line: lineNum, ch: to });
    }
  }
}
function registerWikiImageConverter(plugin) {
  plugin.registerEvent(
    plugin.app.vault.on("create", (abstractFile) => {
      if (!plugin.settings.autoConvertWikiImages)
        return;
      if (!(abstractFile instanceof import_obsidian3.TFile))
        return;
      if (!IMAGE_EXT_RE.test(abstractFile.name))
        return;
      setTimeout(() => {
        const view = plugin.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (!(view == null ? void 0 : view.editor) || !view.file)
          return;
        replaceWikiLinksForFile(view.editor, view.file.path, abstractFile);
      }, 50);
    })
  );
  let debounceTimer = null;
  plugin.registerEvent(
    plugin.app.workspace.on(
      "editor-change",
      (editor, info) => {
        var _a;
        if (!plugin.settings.autoConvertWikiImages)
          return;
        const sourceFilePath = (_a = info.file) == null ? void 0 : _a.path;
        if (!sourceFilePath)
          return;
        const value = editor.getValue();
        if (!value.includes("![["))
          return;
        if (debounceTimer)
          clearTimeout(debounceTimer);
        debounceTimer = setTimeout(() => {
          replaceAllWikiLinksViaCache(editor, sourceFilePath, plugin.app);
        }, 600);
      }
    )
  );
}

// src/processors/crossReference.ts
var COMBINED_RE = /\{#([a-z]+:[^\}]+)\}|\[ref:((?!bib:)[^\]]+)\]/g;
function processTextNode(textNode) {
  var _a;
  const text = (_a = textNode.textContent) != null ? _a : "";
  if (!text.includes("{#") && !text.includes("[ref:"))
    return;
  COMBINED_RE.lastIndex = 0;
  const parts = [];
  let lastIndex = 0;
  let match;
  while ((match = COMBINED_RE.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push({ text: text.slice(lastIndex, match.index), kind: "literal", value: "" });
    }
    if (match[1]) {
      parts.push({ text: match[0], kind: "label", value: match[1] });
    } else if (match[2]) {
      parts.push({ text: match[0], kind: "ref", value: match[2] });
    }
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) {
    parts.push({ text: text.slice(lastIndex), kind: "literal", value: "" });
  }
  if (parts.length === 1 && parts[0].kind === "literal")
    return;
  const parent = textNode.parentNode;
  if (!parent)
    return;
  const fragment = document.createDocumentFragment();
  for (const part of parts) {
    if (part.kind === "literal") {
      fragment.appendChild(document.createTextNode(part.text));
    } else if (part.kind === "label") {
      const span = document.createElement("span");
      span.className = "de-label";
      span.dataset.label = part.value;
      fragment.appendChild(span);
    } else {
      const span = document.createElement("span");
      span.className = "de-ref";
      span.dataset.ref = part.value;
      span.textContent = "[???]";
      fragment.appendChild(span);
    }
  }
  parent.replaceChild(fragment, textNode);
}
function walkTextNodes(el) {
  const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      var _a;
      const parent = node.parentElement;
      if (!parent)
        return NodeFilter.FILTER_SKIP;
      if (parent.closest(".de-label,.de-ref,code,pre,.math"))
        return NodeFilter.FILTER_SKIP;
      const t = (_a = node.textContent) != null ? _a : "";
      return t.includes("{#") || t.includes("[ref:") ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
    }
  });
  const nodes = [];
  let n;
  while (n = walker.nextNode())
    nodes.push(n);
  for (const node of nodes)
    processTextNode(node);
}
function findNearestPreceding(target, container, selector) {
  let nearest = null;
  container.querySelectorAll(selector).forEach((el) => {
    if (el.compareDocumentPosition(target) & Node.DOCUMENT_POSITION_FOLLOWING) {
      nearest = el;
    }
  });
  return nearest;
}
function buildLabelRegistry(container) {
  const registry = /* @__PURE__ */ new Map();
  container.querySelectorAll(".de-label").forEach((labelEl) => {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const fullLabel = (_a = labelEl.dataset.label) != null ? _a : "";
    const colonIdx = fullLabel.indexOf(":");
    if (colonIdx < 0)
      return;
    const type = fullLabel.slice(0, colonIdx);
    let number = "";
    let displayType = "";
    let targetEl = null;
    if (type === "fig") {
      const parentFig = labelEl.closest(".de-figure");
      const fig = parentFig != null ? parentFig : findNearestPreceding(labelEl, container, ".de-figure");
      if (fig) {
        const m = (_c = (_b = fig.querySelector(".de-figcaption")) == null ? void 0 : _b.textContent) == null ? void 0 : _c.match(/図(\d+)/);
        if (m) {
          number = m[1];
          displayType = "fig";
          targetEl = fig;
        }
      }
    } else if (type === "tbl") {
      const tbl = findNearestPreceding(labelEl, container, ".de-table-wrap");
      if (tbl) {
        const m = (_e = (_d = tbl.querySelector(".de-table-caption")) == null ? void 0 : _d.textContent) == null ? void 0 : _e.match(/表(\d+)/);
        if (m) {
          number = m[1];
          displayType = "tbl";
          targetEl = tbl;
        }
      }
    } else if (type === "sec") {
      const heading = labelEl.closest("h1,h2,h3,h4,h5,h6");
      if (heading) {
        const numSpan = heading.querySelector(".de-heading-number");
        if (numSpan) {
          number = ((_f = numSpan.textContent) != null ? _f : "").trim().replace(/\.$/, "");
          displayType = "sec";
          targetEl = heading;
        }
      }
    } else if (type === "eq") {
      const eq = findNearestPreceding(labelEl, container, ".de-equation-wrap");
      if (eq) {
        const m = (_h = (_g = eq.querySelector(".de-equation-number")) == null ? void 0 : _g.textContent) == null ? void 0 : _h.match(/\((\d+)\)/);
        if (m) {
          number = m[1];
          displayType = "eq";
          targetEl = eq;
        }
      }
    }
    if (number && targetEl) {
      const id = `de-anchor-${fullLabel.replace(/[^a-zA-Z0-9]/g, "-")}`;
      targetEl.id = id;
      registry.set(fullLabel, { number, displayType, element: targetEl });
    }
  });
  return registry;
}
function resolveAllReferences(container) {
  const registry = buildLabelRegistry(container);
  container.querySelectorAll(".de-ref").forEach((refEl) => {
    var _a;
    const fullRef = (_a = refEl.dataset.ref) != null ? _a : "";
    const entry = registry.get(fullRef);
    if (!entry) {
      refEl.textContent = "[???]";
      refEl.className = "de-ref de-ref-missing";
      return;
    }
    const { displayType, number, element: targetEl } = entry;
    let displayText = "";
    if (displayType === "fig")
      displayText = `\u56F3${number}`;
    else if (displayType === "tbl")
      displayText = `\u8868${number}`;
    else if (displayType === "sec")
      displayText = number + ".";
    else if (displayType === "eq")
      displayText = `(${number})`;
    else
      displayText = number;
    refEl.textContent = "";
    refEl.className = "de-ref";
    const link = document.createElement("a");
    link.className = "de-ref-link";
    link.textContent = displayText;
    link.href = "#" + targetEl.id;
    link.addEventListener("click", (e) => {
      e.preventDefault();
      targetEl.scrollIntoView({ behavior: "smooth", block: "start" });
    });
    refEl.appendChild(link);
  });
}
var resolveTimer = null;
function scheduleXRefResolution(plugin) {
  if (resolveTimer !== null)
    window.clearTimeout(resolveTimer);
  resolveTimer = window.setTimeout(() => {
    resolveTimer = null;
    plugin.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const view = leaf.view;
      if (view.getMode() === "preview") {
        resolveAllReferences(view.previewMode.containerEl);
      }
    });
  }, 350);
}
function clearXRefTimer() {
  if (resolveTimer !== null) {
    window.clearTimeout(resolveTimer);
    resolveTimer = null;
  }
}
function registerCrossReferenceProcessor(plugin) {
  plugin.registerMarkdownPostProcessor((el) => {
    walkTextNodes(el);
    scheduleXRefResolution(plugin);
  }, 50);
}

// src/processors/equationProcessor.ts
var EquationCounter = class {
  constructor() {
    this.count = 0;
  }
  next() {
    return ++this.count;
  }
  reset() {
    this.count = 0;
  }
};
var BLOCK_MATH_SELECTORS = [
  'mjx-container[display="true"]',
  ".math.math-block"
].join(",");
function wrapEquation(mathEl, n) {
  const wrap = document.createElement("div");
  wrap.className = "de-equation-wrap";
  const numEl = document.createElement("span");
  numEl.className = "de-equation-number";
  numEl.textContent = `(${n})`;
  const parent = mathEl.parentElement;
  if (!parent)
    return;
  parent.insertBefore(wrap, mathEl);
  wrap.appendChild(mathEl);
  wrap.appendChild(numEl);
}
function unwrapEquations(container) {
  container.querySelectorAll(".de-equation-wrap").forEach((wrap) => {
    const parent = wrap.parentNode;
    if (!parent)
      return;
    Array.from(wrap.children).forEach((child) => {
      if (!child.classList.contains("de-equation-number")) {
        parent.insertBefore(child, wrap);
      }
    });
    wrap.remove();
  });
}
function processEquations(el, counter) {
  el.querySelectorAll(BLOCK_MATH_SELECTORS).forEach((mathEl) => {
    if (mathEl.closest(".de-equation-wrap"))
      return;
    wrapEquation(mathEl, counter.next());
  });
}
function processEquationContainer(container, settings) {
  if (!settings.enableEquationNumbers)
    return;
  unwrapEquations(container);
  const counter = new EquationCounter();
  processEquations(container, counter);
}
var SESSION_GAP_MS2 = 500;
function registerEquationPostProcessor(plugin) {
  const counter = new EquationCounter();
  let lastCallTime = 0;
  let lastFile = "";
  plugin.registerMarkdownPostProcessor(
    (el, ctx) => {
      if (!plugin.settings.enableEquationNumbers)
        return;
      const now = Date.now();
      const currentFile = ctx.sourcePath;
      if (currentFile !== lastFile || now - lastCallTime > SESSION_GAP_MS2) {
        counter.reset();
        lastFile = currentFile;
      }
      lastCallTime = now;
      processEquations(el, counter);
      scheduleXRefResolution(plugin);
    },
    20
  );
}

// src/processors/bibliographyProcessor.ts
var BIB_REF_RE = /\[ref:bib:([^\]]+)\]/g;
function processBibRefTextNode(textNode) {
  var _a;
  const text = (_a = textNode.textContent) != null ? _a : "";
  if (!text.includes("[ref:bib:"))
    return;
  BIB_REF_RE.lastIndex = 0;
  const parts = [];
  let lastIndex = 0;
  let match;
  while ((match = BIB_REF_RE.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push({ text: text.slice(lastIndex, match.index), kind: "literal", key: "" });
    }
    parts.push({ text: match[0], kind: "ref", key: match[1] });
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) {
    parts.push({ text: text.slice(lastIndex), kind: "literal", key: "" });
  }
  if (parts.length === 1 && parts[0].kind === "literal")
    return;
  const parent = textNode.parentNode;
  if (!parent)
    return;
  const fragment = document.createDocumentFragment();
  for (const part of parts) {
    if (part.kind === "literal") {
      fragment.appendChild(document.createTextNode(part.text));
    } else {
      const span = document.createElement("span");
      span.className = "de-bib-ref";
      span.dataset.bibKey = part.key;
      span.textContent = "[?]";
      fragment.appendChild(span);
    }
  }
  parent.replaceChild(fragment, textNode);
}
function walkBibRefTextNodes(el) {
  const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      var _a;
      const parent = node.parentElement;
      if (!parent)
        return NodeFilter.FILTER_SKIP;
      if (parent.closest(".de-bib-ref,code,pre"))
        return NodeFilter.FILTER_SKIP;
      return ((_a = node.textContent) != null ? _a : "").includes("[ref:bib:") ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
    }
  });
  const nodes = [];
  let n;
  while (n = walker.nextNode())
    nodes.push(n);
  for (const node of nodes)
    processBibRefTextNode(node);
}
function isBibTable(table) {
  var _a;
  const firstTh = table.querySelector("thead th");
  return ((_a = firstTh == null ? void 0 : firstTh.textContent) != null ? _a : "").trim().toLowerCase() === "key";
}
function getKeyColumnIndex(table) {
  const ths = Array.from(table.querySelectorAll("thead th"));
  return ths.findIndex((th) => {
    var _a;
    return ((_a = th.textContent) == null ? void 0 : _a.trim().toLowerCase()) === "key";
  });
}
function collectBibEntries(container) {
  const entries = /* @__PURE__ */ new Map();
  let tableOrder = 0;
  container.querySelectorAll("table").forEach((table) => {
    if (!isBibTable(table))
      return;
    const keyCol = getKeyColumnIndex(table);
    if (keyCol < 0)
      return;
    const rows = Array.from(table.querySelectorAll("tbody tr"));
    rows.forEach((row) => {
      var _a, _b;
      const cell = row.cells[keyCol];
      if (!cell)
        return;
      const key = ((_b = (_a = cell.dataset.bibOrigKey) != null ? _a : cell.textContent) != null ? _b : "").trim();
      if (!key)
        return;
      cell.dataset.bibOrigKey = key;
      entries.set(key, { rowEl: row, tableOrder: tableOrder++ });
    });
    table.classList.add("de-bib-table");
  });
  return entries;
}
function collectCitationOrder(container) {
  const keys = [];
  const seen = /* @__PURE__ */ new Set();
  container.querySelectorAll(".de-bib-ref").forEach((span) => {
    var _a;
    const key = (_a = span.dataset.bibKey) != null ? _a : "";
    if (key && !seen.has(key)) {
      seen.add(key);
      keys.push(key);
    }
  });
  return keys;
}
function applyBibNumbers(container, entries, orderedKeys, keyToNumber) {
  entries.forEach((entry, key) => {
    var _a;
    const n = keyToNumber.get(key);
    if (n === void 0)
      return;
    const table = entry.rowEl.closest("table");
    if (!table)
      return;
    const keyCol = getKeyColumnIndex(table);
    const cell = entry.rowEl.cells[keyCol];
    if (!cell)
      return;
    const origKey = (_a = cell.dataset.bibOrigKey) != null ? _a : key;
    const anchorId = `de-bib-${origKey.replace(/[^a-zA-Z0-9]/g, "-")}`;
    entry.rowEl.id = anchorId;
    cell.textContent = "";
    const numSpan = document.createElement("span");
    numSpan.className = "de-bib-number";
    numSpan.textContent = `[${n}]`;
    const keyText = document.createTextNode(` ${origKey}`);
    cell.appendChild(numSpan);
    cell.appendChild(keyText);
  });
  container.querySelectorAll(".de-bib-ref").forEach((span) => {
    var _a;
    const key = (_a = span.dataset.bibKey) != null ? _a : "";
    const n = keyToNumber.get(key);
    if (n === void 0) {
      span.textContent = "[?]";
      span.className = "de-bib-ref de-ref-missing";
      return;
    }
    const entry = entries.get(key);
    span.textContent = "";
    span.className = "de-bib-ref";
    const link = document.createElement("a");
    link.className = "de-ref-link";
    link.textContent = `[${n}]`;
    if (entry) {
      const anchorId = entry.rowEl.id;
      link.href = "#" + anchorId;
      link.addEventListener("click", (e) => {
        e.preventDefault();
        entry.rowEl.scrollIntoView({ behavior: "smooth", block: "start" });
      });
    }
    span.appendChild(link);
  });
}
function resolveBibliography(container, order) {
  container.querySelectorAll("[data-bib-orig-key]").forEach((cell) => {
    var _a;
    const origKey = (_a = cell.dataset.bibOrigKey) != null ? _a : "";
    cell.textContent = origKey;
  });
  const entries = collectBibEntries(container);
  if (entries.size === 0)
    return;
  const keyToNumber = /* @__PURE__ */ new Map();
  if (order === "citation") {
    const citationKeys = collectCitationOrder(container);
    let n = 1;
    for (const key of citationKeys) {
      if (entries.has(key))
        keyToNumber.set(key, n++);
    }
    entries.forEach((_, key) => {
      if (!keyToNumber.has(key))
        keyToNumber.set(key, n++);
    });
  } else {
    const sorted = Array.from(entries.entries()).sort(
      (a, b) => a[1].tableOrder - b[1].tableOrder
    );
    sorted.forEach(([key], idx) => keyToNumber.set(key, idx + 1));
  }
  applyBibNumbers(container, entries, [], keyToNumber);
}
var bibTimer = null;
function scheduleBibResolution(plugin) {
  if (bibTimer !== null)
    window.clearTimeout(bibTimer);
  bibTimer = window.setTimeout(() => {
    bibTimer = null;
    plugin.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const view = leaf.view;
      if (view.getMode() === "preview") {
        resolveBibliography(
          view.previewMode.containerEl,
          plugin.settings.bibNumberingOrder
        );
      }
    });
  }, 400);
}
function clearBibTimer() {
  if (bibTimer !== null) {
    window.clearTimeout(bibTimer);
    bibTimer = null;
  }
}
function processBibliographyContainer(container, settings) {
  if (!settings.enableBibliography)
    return;
  resolveBibliography(container, settings.bibNumberingOrder);
}
function registerBibliographyPostProcessor(plugin) {
  plugin.registerMarkdownPostProcessor((el) => {
    if (!plugin.settings.enableBibliography)
      return;
    walkBibRefTextNodes(el);
    scheduleBibResolution(plugin);
  }, 60);
}

// src/features/tocGenerator.ts
var import_obsidian4 = require("obsidian");
var TOC_START = "<!-- TOC -->";
var TOC_END = "<!-- /TOC -->";
function generateToc(content) {
  const counter = new HeadingCounter();
  const lines = content.split("\n");
  const tocLines = [TOC_START];
  for (const line of lines) {
    if (line === TOC_START || line === TOC_END)
      continue;
    const m = line.match(/^(#{1,3}) (.+)/);
    if (!m)
      continue;
    const level = m[1].length;
    const text = m[2].replace(/\{#[^\}]+\}/g, "").trim();
    const number = counter.next(level);
    const indent = "  ".repeat(level - 1);
    tocLines.push(`${indent}- ${number} ${text}`);
  }
  tocLines.push(TOC_END);
  return tocLines.join("\n");
}
function findExistingTocRange(content) {
  const lines = content.split("\n");
  let startLine = -1;
  let endLine = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trimEnd() === TOC_START)
      startLine = i;
    if (lines[i].trimEnd() === TOC_END && startLine >= 0) {
      endLine = i;
      break;
    }
  }
  if (startLine < 0 || endLine < 0)
    return null;
  return { startLine, endLine };
}
function registerTocCommands(plugin) {
  plugin.addCommand({
    id: "insert-toc-at-cursor",
    name: "TOC\u3092\u30AB\u30FC\u30BD\u30EB\u4F4D\u7F6E\u306B\u633F\u5165",
    editorCallback: (editor) => {
      const toc = generateToc(editor.getValue());
      editor.replaceSelection(toc + "\n\n");
    }
  });
  plugin.addCommand({
    id: "insert-toc-at-top",
    name: "TOC\u3092\u30D5\u30A1\u30A4\u30EB\u5148\u982D\u306B\u633F\u5165",
    editorCallback: (editor) => {
      const toc = generateToc(editor.getValue());
      editor.replaceRange(toc + "\n\n", { line: 0, ch: 0 });
    }
  });
  plugin.addCommand({
    id: "update-toc",
    name: "\u65E2\u5B58TOC\u3092\u66F4\u65B0",
    editorCallback: (editor) => {
      const content = editor.getValue();
      const range = findExistingTocRange(content);
      if (!range) {
        const toc2 = generateToc(content);
        editor.replaceSelection(toc2 + "\n\n");
        return;
      }
      const toc = generateToc(content);
      editor.replaceRange(
        toc,
        { line: range.startLine, ch: 0 },
        { line: range.endLine, ch: TOC_END.length }
      );
    }
  });
  plugin.addCommand({
    id: "refresh-toc-reading-view",
    name: "TOC\u3092\u518D\u63CF\u753B (Reading View)",
    checkCallback: (checking) => {
      const view = plugin.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
      if (!view || view.getMode() !== "preview")
        return false;
      if (checking)
        return true;
      view.previewMode.rerender(true);
      return true;
    }
  });
}

// src/features/pdfExporter.ts
var import_obsidian5 = require("obsidian");
function getElectronRemote() {
  var _a;
  try {
    const electron = window.require("electron");
    return (_a = electron.remote) != null ? _a : null;
  } catch (e) {
    return null;
  }
}
var PdfExportModal = class extends import_obsidian5.Modal {
  constructor(app, plugin) {
    var _a, _b;
    super(app);
    this.previewTimer = null;
    this.plugin = plugin;
    this.fontSize = plugin.settings.defaultPdfFontSize;
    this.margin = plugin.settings.defaultPdfMargin;
    const activeFile = (_a = app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView)) == null ? void 0 : _a.file;
    this.filename = ((_b = activeFile == null ? void 0 : activeFile.basename) != null ? _b : "document") + ".pdf";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("de-pdf-modal-container");
    const layout = contentEl.createDiv({ cls: "de-pdf-modal" });
    const settingsEl = layout.createDiv({ cls: "de-pdf-settings" });
    const previewWrap = layout.createDiv({ cls: "de-pdf-preview-wrap" });
    previewWrap.createSpan({ text: "A4 \u30D7\u30EC\u30D3\u30E5\u30FC", cls: "de-pdf-preview-label" });
    this.previewContentEl = previewWrap.createDiv({ cls: "de-pdf-preview-content" });
    this.applyPreviewStyles();
    settingsEl.createEl("h3", { text: "PDF\u51FA\u529B\u8A2D\u5B9A" });
    new import_obsidian5.Setting(settingsEl).setName(`\u672C\u6587\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA: ${this.fontSize}pt`).addSlider((sl) => sl.setLimits(9, 14, 1).setValue(this.fontSize).setDynamicTooltip().onChange((val) => {
      var _a, _b, _c, _d;
      this.fontSize = val;
      (_a = sl.sliderEl.previousElementSibling) == null ? void 0 : _a.remove();
      (_d = (_c = (_b = sl.sliderEl.parentElement) == null ? void 0 : _b.previousElementSibling) == null ? void 0 : _c.setText) == null ? void 0 : _d.call(_c, `\u672C\u6587\u30D5\u30A9\u30F3\u30C8\u30B5\u30A4\u30BA: ${val}pt`);
      this.schedulePreviewUpdate();
    }));
    new import_obsidian5.Setting(settingsEl).setName(`\u4F59\u767D: ${this.margin}mm`).addSlider((sl) => sl.setLimits(10, 30, 5).setValue(this.margin).setDynamicTooltip().onChange((val) => {
      this.margin = val;
      this.schedulePreviewUpdate();
    }));
    new import_obsidian5.Setting(settingsEl).setName("\u51FA\u529B\u30D5\u30A1\u30A4\u30EB\u540D").addText((text) => text.setValue(this.filename).onChange((val) => {
      this.filename = val || this.filename;
    }));
    settingsEl.createEl("button", { text: "PDF\u3092\u51FA\u529B", cls: "mod-cta de-pdf-export-btn" }).addEventListener("click", () => void this.exportPdf());
    void this.updatePreview();
  }
  applyPreviewStyles() {
    this.previewContentEl.style.padding = `${this.margin}mm`;
    this.previewContentEl.style.fontSize = `${this.fontSize}pt`;
    this.previewContentEl.style.lineHeight = "1.6";
    this.previewContentEl.style.maxWidth = "210mm";
    this.previewContentEl.style.background = "#fff";
    this.previewContentEl.style.color = "#000";
  }
  schedulePreviewUpdate() {
    if (this.previewTimer !== null)
      window.clearTimeout(this.previewTimer);
    this.previewTimer = window.setTimeout(() => {
      this.previewTimer = null;
      void this.updatePreview();
    }, 500);
  }
  async updatePreview() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (!(view == null ? void 0 : view.file)) {
      this.previewContentEl.textContent = "\u30A2\u30AF\u30C6\u30A3\u30D6\u306AMarkdown\u30D5\u30A1\u30A4\u30EB\u304C\u3042\u308A\u307E\u305B\u3093\u3002";
      return;
    }
    this.previewContentEl.empty();
    this.applyPreviewStyles();
    const content = await this.app.vault.read(view.file);
    await import_obsidian5.MarkdownRenderer.render(
      this.app,
      content,
      this.previewContentEl,
      view.file.path,
      view
    );
  }
  async exportPdf() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (!(view == null ? void 0 : view.file)) {
      new import_obsidian5.Notice("\u30A2\u30AF\u30C6\u30A3\u30D6\u306AMarkdown\u30D5\u30A1\u30A4\u30EB\u304C\u3042\u308A\u307E\u305B\u3093\u3002");
      return;
    }
    const filename = this.filename.endsWith(".pdf") ? this.filename : this.filename + ".pdf";
    const remote = getElectronRemote();
    if (remote) {
      await this.exportWithElectron(remote, filename);
    } else {
      this.exportWithPrint();
    }
  }
  async exportWithElectron(remote, filename) {
    try {
      new import_obsidian5.Notice("PDF\u751F\u6210\u4E2D...");
      const win = remote.getCurrentWindow();
      const pdfBuffer = await win.webContents.printToPDF({
        pageSize: "A4",
        printBackground: true,
        margins: {
          marginType: "custom",
          top: this.margin / 25.4,
          // mm → inches
          bottom: this.margin / 25.4,
          left: this.margin / 25.4,
          right: this.margin / 25.4
        }
      });
      const outputPath = filename;
      const exists = await this.app.vault.adapter.exists(outputPath);
      if (exists) {
        await this.app.vault.adapter.writeBinary(outputPath, pdfBuffer);
      } else {
        await this.app.vault.adapter.writeBinary(outputPath, pdfBuffer);
      }
      new import_obsidian5.Notice(`PDF\u4FDD\u5B58\u5B8C\u4E86: ${filename}`);
      this.close();
    } catch (err) {
      console.error("PDF export error:", err);
      new import_obsidian5.Notice(`PDF\u751F\u6210\u30A8\u30E9\u30FC: ${String(err)}
\u30D6\u30E9\u30A6\u30B6\u5370\u5237\u3067\u304A\u8A66\u3057\u304F\u3060\u3055\u3044\u3002`);
      this.exportWithPrint();
    }
  }
  exportWithPrint() {
    const printWin = window.open("", "_blank");
    if (!printWin) {
      new import_obsidian5.Notice("\u30DD\u30C3\u30D7\u30A2\u30C3\u30D7\u304C\u30D6\u30ED\u30C3\u30AF\u3055\u308C\u307E\u3057\u305F\u3002");
      return;
    }
    printWin.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${this.filename}</title>
        <style>
          @page { size: A4; margin: ${this.margin}mm; }
          body { font-size: ${this.fontSize}pt; line-height: 1.6; font-family: serif; }
        </style>
      </head>
      <body>
        ${this.previewContentEl.innerHTML}
      </body>
      </html>
    `);
    printWin.document.close();
    printWin.focus();
    printWin.print();
    printWin.close();
  }
  onClose() {
    if (this.previewTimer !== null) {
      window.clearTimeout(this.previewTimer);
      this.previewTimer = null;
    }
    this.contentEl.empty();
  }
};
function registerPdfExporter(plugin) {
  plugin.addCommand({
    id: "export-pdf",
    name: "PDF\u3092\u51FA\u529B",
    callback: () => {
      new PdfExportModal(plugin.app, plugin).open();
    }
  });
  plugin.addRibbonIcon("file-text", "PDF\u3092\u51FA\u529B (Document Editor)", () => {
    new PdfExportModal(plugin.app, plugin).open();
  });
}

// src/main.ts
var DocumentEditorPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.rerenderTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new DocumentEditorSettingTab(this.app, this));
    this.registerEditorExtension(createHeadingNumberPlugin(this));
    registerHeadingPostProcessor(this);
    registerFigurePostProcessor(this);
    registerWikiImageConverter(this);
    registerCrossReferenceProcessor(this);
    registerEquationPostProcessor(this);
    registerBibliographyPostProcessor(this);
    registerTocCommands(this);
    registerPdfExporter(this);
    this.app.workspace.onLayoutReady(() => {
      this.scheduleRerender(800);
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.scheduleRerender(300);
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.scheduleRerender(300);
      })
    );
    this.addCommand({
      id: "rerender-figures",
      name: "\u56F3\u8868\u30FB\u6570\u5F0F\u30FB\u53C2\u8003\u6587\u732E\u3092\u30EA\u30D5\u30EC\u30C3\u30B7\u30E5",
      callback: () => {
        this.rerenderAllReadingViews();
      }
    });
    this.addRibbonIcon("refresh-cw", "\u56F3\u8868\u756A\u53F7\u3092\u30EA\u30D5\u30EC\u30C3\u30B7\u30E5 (Document Editor)", () => {
      this.rerenderAllReadingViews();
    });
    console.log("Document Editor: loaded");
  }
  scheduleRerender(delay) {
    if (this.rerenderTimer !== null)
      window.clearTimeout(this.rerenderTimer);
    this.rerenderTimer = window.setTimeout(() => {
      this.rerenderTimer = null;
      this.rerenderAllReadingViews();
    }, delay);
  }
  rerenderAllReadingViews() {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const view = leaf.view;
      if (view.getMode() !== "preview")
        return;
      const container = view.previewMode.containerEl;
      processFigureContainer(container, this.settings);
      processEquationContainer(container, this.settings);
      processBibliographyContainer(container, this.settings);
      scheduleXRefResolution(this);
    });
  }
  onunload() {
    if (this.rerenderTimer !== null)
      window.clearTimeout(this.rerenderTimer);
    clearXRefTimer();
    clearBibTimer();
    console.log("Document Editor: unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
